include:
  - path: ./compose-infra.yaml

services:
  amachat-cli:
    build: .
    command: bun dev:docker
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/ # Check Dockerfile WORKDIR
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - BASE_OLLAMA_URL=http://ollama:11434
      - BASE_CHROMA_URL=http://chroma:8000
      - DOCKER_ENV=true
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - service-network
    depends_on:
      - ollama
      - chroma
  amachat-http:
    build: .
    command: bun dev:docker:server
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/ # Check Dockerfile WORKDIR
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - BASE_OLLAMA_URL=http://ollama:11434
      - BASE_CHROMA_URL=http://chroma:8000
      - DOCKER_ENV=true
      - GROQ_API_KEY=${GROQ_API_KEY}

    ports:
      - '3000:3000'
    networks:
      - service-network
    depends_on:
      - ollama
      - chroma

networks:
  service-network:
    driver: bridge
