on:
  pull_request:
    branches:
      - 09-19-debug_and_make_the_model_pull_successfull_from_app

jobs:
  run:
    name: Directly run the app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: List files in home
        run: ls $HOME
      - name: List files in action folder
        run: ls ${{ github.path }}
      - name: List the files in the present working directory
        run: echo $pwd
      - name: List files in src directory
        run: ls ./src
      - name: Build and run the app
        # Will bun is available in this step
        run: |
          # ls $pwd
          # $HOME/.bun/bin/bun install
          # $HOME/.bun/bin/bun ./src/ama.ts
          echo "TODO need to run deps separately"
