on:
  pull_request:
    branches:
    - main

jobs:
  run:
    name: Directly run the app
    runs-on: ubuntu-latest
    steps:
     - name: Build and run the app
       run: |
         echo "$HOME/.bun/bin" >> $GITHUB_PATH
         curl -fsSL https://bun.sh/install | bash
         source $HOME/.bashrc
         cat $HOME/.bashrc
         $HOME/.bun/bin/bun dev
