on:
  pull_request:
    branches:
    - main

jobs:
  run:
    name: Directly run the app
    runs-on: ubuntu-latest
    steps:
     - name: Build and run the app
       run: |
         curl -fsSL https://bun.sh/install | bash
         echo "$HOME/.bun/bin" >> $GITHUB_PATH
         source $HOME/.bashrc
         bun dev
