on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and run services for LLM app
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
      - name: Build and start
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: docker compose up --build
     
