on:
  pull_request:
    branches:
      - main

jobs:
  build:
     name: Build and run services for LLM app
     runs-on: ubuntu-latest
     steps:
       - run: docker compose --file ${{ github.action_path }}/compose.yaml up --build
     
