on:
  pull_request:
    branches:
      - 09-19-debug_and_make_the_model_pull_successfull_from_app

jobs:
  build:
    name: Build and run services for LLM app
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
      - name: Build and start
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          docker compose build
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} docker compose up
     
